### ISSUE TITLE
Cannot read property 'prototype' of undefined in canvas-utilities.js

### ISSUE THREAD

**Issue by thomasleese** [beaugunderson/cat-snacks#10]
When I run `npm install` and then `npm start`, I get this error message in my browser:

<img width="1280" alt="screen shot 2016-02-01 at 08 51 28" src="https://cloud.githubusercontent.com/assets/510498/12712545/02e82c04-c8c1-11e5-80a0-2718c6187833.png">

I'm using Node 5.5.0 and NPM 3.3.12. The issue seems to be related to the fact that `Canvas.Context2d` is `undefined`:

<img width="381" alt="screen shot 2016-02-01 at 08 52 04" src="https://cloud.githubusercontent.com/assets/510498/12712566/208ee414-c8c1-11e5-9d76-1ca07e47fa84.png">

**Comment by beaugunderson** [comment]
ah, sorry! this is an issue in canvas-utilities that I fixed locally but haven't published yet--doing so momentarily

---

**Comment by beaugunderson** [comment]
ok, `git pull`, `npm install`, and all should be well :)

**Comment by thomasleese** [comment]
Awesome, it works! :smile_cat:
