### ISSUE TITLE
Dev seems to be OS X-only(?)

### ISSUE THREAD

**Issue by su** [beaugunderson/cat-snacks#15]
Something somewhere in the code(it's not in the package.json file) is calling for the fsevents module. 
After some failed install attempts and less-than-informative error messages on Win7, a Pi I've been playing with finally spit up an error that suggests it only supports OS X, which the [module page](https://www.npmjs.com/package/fsevents) *kiiiinda* says, if you're looking for it. There's also a suggestion for a cross-platform replacement, but I have no idea how plausible that is to swap in since I don't even know where this requirement is coming from right now.

So…FYI, I guess.

**Comment by beaugunderson** [comment]
thanks for reporting this, it's definitely not intentional!

we do have some modules that rely on chokidar, which is the cross-platform module that is using fsevents under the hood; if this is what you're seeing then you should be able to safely ignore it:

![screenshot](https://i.imgur.com/ILb5mrn.png)

chokidar tries to use fsevents under the hood if it's able to and falls back to something else if it's not. :)

i have a windows machine as well and i'll test that everything is working there.

**Comment by su** [comment]
Ugh. Yeah, it is a `warn` but there was no mention of chokidar in the message I got. Or even the second line under Windows; that only showed up on the Pi. I'll have another look and see if this all matches up. I was kind of at the end of trying/caring by that point. (Hi. I barely know what I'm doing.)

If that's the case, then I think the ultimate failure is probably due to something else about another module(gyp, I think) not liking my Python version, apparently for being *too current*, which I haven't checked on yet.

**Comment by beaugunderson** [comment]
it just struck me that the `canvas` module is only useful for generating images on the server side (to make the images that appear in @catsnacks' tweets, for example) and so it's probably fine to make it an optional dependency! i think this will make things a lot easier for you but let me give it a try real quick :)

**Comment by beaugunderson** [comment]
ok, i made `canvas` an optionalDependency of `canvas-utilities`; that piece may still fail when you `npm install` but the browser-based dev server will still work (you can start it with `npm start`)

`git pull` to update to the latest cat-snacks and let me know if that works :)

**Comment by su** [comment]
It worked! The dev server, too. (Windows, anyway. I'll poke the Pi on the weekend or something, just to check.) Still get the complaint about the Python version, but it's not blocking anything, it seems.

Now to see if I can figure out how to draw something and have it show up where intended.
